In [1]:
from sklearn.feature_extraction.text import CountVectorizer

query = ['波斯湾 伊拉克 原油']

'''
corpus = [ 'This is the first document.',
           'This is the second second document.',
           'And the third one.',
           'Is this the first document?'
         ]


corpus = [ '加势大周 日本 广告 可口可乐',
           '伊拉克 原油 科威特 波斯湾 沙特阿拉伯',
           '原油 科威特 波斯湾 沙特阿拉伯',
           '新世航一号 渔船 喋血案 游闻道 吕政道',
           '新世航 渔船 喋血案 刘宪助'
         ]
'''

corpus = []

with open('document.txt', 'r', encoding='utf-8') as f:
    for line in f:
        corpus.append(line.strip('\n'))


print(corpus)

#min_df=Specifies the minimum number of different documents a term must appear in to be included in the vocabulary
vectorizer = CountVectorizer(min_df=1)

#得到TF Matrix
X = vectorizer.fit_transform(corpus)
print (X)
print (X.toarray())

#词的对应索引值
feature_name = vectorizer.get_feature_names()
print (feature_name)

#Transform Query to KW Vector
Q = vectorizer.transform(query)
print(Q.toarray())

['加势大周 日本 广告 可口可乐', '伊拉克 原油 科威特 波斯湾 沙特阿拉伯', '原油 科威特 波斯湾 沙特阿拉伯', '新世航一号 渔船 喋血案 游闻道 吕政道', '新世航 渔船 喋血案 刘宪助']
  (0, 4)	1
  (0, 7)	1
  (0, 10)	1
  (0, 2)	1
  (1, 11)	1
  (1, 12)	1
  (1, 15)	1
  (1, 3)	1
  (1, 0)	1
  (2, 11)	1
  (2, 12)	1
  (2, 15)	1
  (2, 3)	1
  (3, 5)	1
  (3, 14)	1
  (3, 6)	1
  (3, 13)	1
  (3, 9)	1
  (4, 1)	1
  (4, 8)	1
  (4, 6)	1
  (4, 13)	1
[[0 0 1 0 1 0 0 1 0 0 1 0 0 0 0 0]
 [1 0 0 1 0 0 0 0 0 0 0 1 1 0 0 1]
 [0 0 0 1 0 0 0 0 0 0 0 1 1 0 0 1]
 [0 0 0 0 0 1 1 0 0 1 0 0 0 1 1 0]
 [0 1 0 0 0 0 1 0 1 0 0 0 0 1 0 0]]
['伊拉克', '刘宪助', '加势大周', '原油', '可口可乐', '吕政道', '喋血案', '广告', '新世航', '新世航一号', '日本', '沙特阿拉伯', '波斯湾', '渔船', '游闻道', '科威特']
[[1 0 0 1 0 0 0 0 0 0 0 0 1 0 0 0]]


In [2]:
from sklearn.feature_extraction.text import TfidfTransformer 

transformer = TfidfTransformer(smooth_idf=True)

tfidf = transformer.fit_transform(X) 
print (tfidf)
print (tfidf.toarray())

print(transformer.transform(Q).toarray())

for i in range(len(corpus)):
    print(sum(transformer.transform(Q).toarray()[0] * tfidf.toarray()[i]))

  (0, 10)	0.5
  (0, 7)	0.5
  (0, 4)	0.5
  (0, 2)	0.5
  (1, 15)	0.4250013751329181
  (1, 12)	0.4250013751329181
  (1, 11)	0.4250013751329181
  (1, 3)	0.4250013751329181
  (1, 0)	0.52677824987419
  (2, 15)	0.5
  (2, 12)	0.5
  (2, 11)	0.5
  (2, 3)	0.5
  (3, 14)	0.4821401170833009
  (3, 13)	0.3889876106617681
  (3, 9)	0.4821401170833009
  (3, 6)	0.3889876106617681
  (3, 5)	0.4821401170833009
  (4, 13)	0.44400207886377085
  (4, 8)	0.5503291323968319
  (4, 6)	0.44400207886377085
  (4, 1)	0.5503291323968319
[[0.         0.         0.5        0.         0.5        0.
  0.         0.5        0.         0.         0.5        0.
  0.         0.         0.         0.        ]
 [0.52677825 0.         0.         0.42500138 0.         0.
  0.         0.         0.         0.         0.         0.42500138
  0.42500138 0.         0.         0.42500138]
 [0.         0.         0.         0.5        0.         0.
  0.         0.         0.         0.         0.         0.5
  0.5        0.         0.     

In [8]:
import numpy as np
d1 = [0.602, 0.602, 0.602, 0.301, 0, 0, 0, 0, 0, 0, 0]
d2 = [0,0.301,0,0.301,0.602,0,0,0,0,0,0]
d3 = [0,0,0,0,0,0.602,0.301,0.301,0.602,0,0]
d4 = [0,0,0,0,0,0,0.602,0.602,0,0.602,0.602]
q1 = [0.602, 0.301, 0, 0.301, 0, 0, 0, 0, 0, 0, 0]
q2 = [0,0,0,0,0,0.602,0,0,0,0,0]

print (cosine_similarity(np.mat(d1),np.mat(q1)))
print (cosine_similarity(np.mat(d2),np.mat(q1)))
print (cosine_similarity(np.mat(d3),np.mat(q1)))
print (cosine_similarity(np.mat(d4),np.mat(q1)))

print (cosine_similarity(np.mat(d1),np.mat(q2)))
print (cosine_similarity(np.mat(d2),np.mat(q2)))
print (cosine_similarity(np.mat(d3),np.mat(q2)))
print (cosine_similarity(np.mat(d4),np.mat(q2)))

[[0.79259392]]
[[0.33333333]]
[[0.]]
[[0.]]
[[0.]]
[[0.]]
[[0.63245553]]
[[0.]]


In [9]:
from sklearn.feature_extraction.text import TfidfVectorizer
import numpy as np

vectorizer2 = TfidfVectorizer(smooth_idf=True)

tfidf2 = vectorizer2.fit_transform(corpus)
print (tfidf2)
print (tfidf2.toarray())
print (vectorizer2.transform(query).toarray())

# 计算查询与文件间的相似度
for i in range(len(corpus)):
    print(cosine_similarity(vectorizer2.transform(query).toarray(),np.mat(tfidf2.toarray()[i])))

  (0, 2)	0.5
  (0, 10)	0.5
  (0, 7)	0.5
  (0, 4)	0.5
  (1, 0)	0.52677824987419
  (1, 3)	0.4250013751329181
  (1, 15)	0.4250013751329181
  (1, 12)	0.4250013751329181
  (1, 11)	0.4250013751329181
  (2, 3)	0.5
  (2, 15)	0.5
  (2, 12)	0.5
  (2, 11)	0.5
  (3, 9)	0.4821401170833009
  (3, 13)	0.3889876106617681
  (3, 6)	0.3889876106617681
  (3, 14)	0.4821401170833009
  (3, 5)	0.4821401170833009
  (4, 13)	0.44400207886377085
  (4, 6)	0.44400207886377085
  (4, 8)	0.5503291323968319
  (4, 1)	0.5503291323968319
[[0.         0.         0.5        0.         0.5        0.
  0.         0.5        0.         0.         0.5        0.
  0.         0.         0.         0.        ]
 [0.52677825 0.         0.         0.42500138 0.         0.
  0.         0.         0.         0.         0.         0.42500138
  0.42500138 0.         0.         0.42500138]
 [0.         0.         0.         0.5        0.         0.
  0.         0.         0.         0.         0.         0.5
  0.5        0.         0.     